language: php

php:
  - 5.3
  - 5.3.3
  - 5.4
  - 5.5

env:
  - CAKE_VERSION=master

before_script:
  - sh -c "mysql -e 'CREATE DATABASE cakephp_test;'"
  - git clone --depth 1 git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp && git checkout $CAKE_VERSION
  - cp -R ../Ratchet plugins/Ratchet
  - chmod -R 777 ../cakephp/app/tmp
  - set +H
  - echo "<?php
    class DATABASE_CONFIG {
    public \$test = array(
      'datasource' => 'Database/Mysql',
      'database' => 'cakephp_test',
      'host' => '0.0.0.0',
      'login' => 'travis'
      'host' => '',
      'persistent' => false,
    );
    }" > ../cakephp/app/Config/database.php

script:
  - ./lib/Cake/Console/cake test Ratchet AllRatchetTestsTest --stderr
  
notifications:
  webhooks:
    urls: 
      - http://wyrihaximus.net/wyri_projects/wyri_projects/webhook/travisci.json
    on_success: always
    on_failure: always
    on_start: true