language: php

php:
  - 5.3
  - 5.3.3
  - 5.4
  - 5.5

env:
  - CAKE_VERSION=master

before_script:
  - sh -c "mysql -e 'CREATE DATABASE cakephp_test;'"
  - cd ../../
  - git clone --depth=50 --branch=master git://github.com/markstory/asset_compress.git markstory/asset_compress
  - cd WyriHaximus/Ratchet
  - git clone --depth 1 git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp && git checkout $CAKE_VERSION
  - cp -R ../Ratchet plugins/Ratchet
  - cp -R ../../markstory/asset_compress plugins/AssetCompress
  - chmod -R 777 ../cakephp/app/tmp
  - set +H
  - echo "<?php
    class DATABASE_CONFIG {
    public \$test = array(
      'datasource' => 'Database/Mysql',
      'database' => 'cakephp_test',
      'host' => '0.0.0.0',
      'login' => 'travis'
      'host' => '',
      'persistent' => false,
    );
    }" > ../cakephp/app/Config/database.php
  - echo "
[js]
paths[] = WEBROOT/js/*
cachePath = WEBROOT/js/cache
[css]
paths[] = WEBROOT/css/*
cachePath = WEBROOT/css/cache
    " >> ../cakephp/app/Config/asset_compress.ini

script:
  - ./lib/Cake/Console/cake test Ratchet AllRatchetTests --stderr
  
notifications:
  webhooks:
    urls: 
      - http://wyrihaximus.net/wyri_projects/wyri_projects/webhook/travisci.json
    on_success: always
    on_failure: always
    on_start: true